keys:
  - &rpi age1rqe8h2y98sn903wzz97ewh90qze2n7xyyuaw3mj4r8n65zvhm9jswrxsaq
  - &kuro age1wvzsz6fz3fuqpa0fdym57fn57tja4gnq3dfukjtuwl85rj93uagsusj7ye

creation_rules:
  - path_regex: secrets\.yaml$
    key_groups:
      - age:
          - *rpi
          - *kuro